In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('archivo_nptas.csv')
df

   columna_1   columna_2   columna_3
0          4           5           6
1          7           8           9

In [20]:
list = [1, 2, 3, 4, 5, 6, 7, 8]
list2 = [22, 2, 3, 4, 5, 6, 7, 8]
list3 = [65, 2, 3, 4, 5, 6, 7, 8]

dataframe = pd.DataFrame([list, list2, list3], columns=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
dataframe

    a  b  c  d  e  f  g  h
0   1  2  3  4  5  6  7  8
1  22  2  3  4  5  6  7  8
2  65  2  3  4  5  6  7  8

In [21]:
dataframe.describe()

               a    b    c    d    e    f    g    h
count   3.000000  3.0  3.0  3.0  3.0  3.0  3.0  3.0
mean   29.333333  2.0  3.0  4.0  5.0  6.0  7.0  8.0
std    32.624122  0.0  0.0  0.0  0.0  0.0  0.0  0.0
min     1.000000  2.0  3.0  4.0  5.0  6.0  7.0  8.0
25%    11.500000  2.0  3.0  4.0  5.0  6.0  7.0  8.0
50%    22.000000  2.0  3.0  4.0  5.0  6.0  7.0  8.0
75%    43.500000  2.0  3.0  4.0  5.0  6.0  7.0  8.0
max    65.000000  2.0  3.0  4.0  5.0  6.0  7.0  8.0

In [22]:

dataframe['a'].unique()

array([ 1, 22, 65])

In [23]:
dataframe.shape

(3, 8)

In [24]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       3 non-null      int64
 4   e       3 non-null      int64
 5   f       3 non-null      int64
 6   g       3 non-null      int64
 7   h       3 non-null      int64
dtypes: int64(8)
memory usage: 324.0 bytes

In [25]:
dataframe.size

24

In [26]:
dataframe.loc[0, 'b'] = 90
dataframe

    a   b  c  d  e  f  g  h
0   1  90  3  4  5  6  7  8
1  22   2  3  4  5  6  7  8
2  65   2  3  4  5  6  7  8