In [3]:
import pandas as pd

In [11]:
results = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv')
results.head(8)
results.tail(20)
results.sample(5)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
135421,NaN,NaN,Athletics,"1,500 metres, Men (Intercalated)",Felix Kwieton,64914,AUT,NaN,2.0,False,NaN
182060,1976.0,Winter,Biathlon,"20 kilometres, Men (Olympic)",Svein Engen,85515,NOR,NaN,20.0,False,NaN
272494,2014.0,Winter,Biathlon,"15 kilometres, Women (Olympic)",Eva Puskarčíková,127593,CZE,NaN,21.0,False,NaN
240513,2014.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Ville Nousiainen,111055,FIN,NaN,28.0,False,NaN
79395,1984.0,Summer,Rowing,"Coxed Pairs, Men (Olympic)",Guy Defraigne,35679,BEL,Belgium,11.0,False,NaN

In [18]:
# [rows, columns]

# results.loc[[ 79395, 200, 2000 ], [ 'event', 'discipline' ]]
results.loc[70000:, [ 'event', 'discipline' ]]

                                       event                        discipline
70000   Individual All-Around, Men (Olympic)  Artistic Gymnastics (Gymnastics)
70001          Floor Exercise, Men (Olympic)  Artistic Gymnastics (Gymnastics)
70002             Horse Vault, Men (Olympic)  Artistic Gymnastics (Gymnastics)
70003           Parallel Bars, Men (Olympic)  Artistic Gymnastics (Gymnastics)
70004          Horizontal Bar, Men (Olympic)  Artistic Gymnastics (Gymnastics)
...                                      ...                               ...
308403                Singles, Men (Olympic)                              Luge
308404               Slalom, Women (Olympic)            Alpine Skiing (Skiing)
308405                 Team, Mixed (Olympic)            Alpine Skiing (Skiing)
308406         Giant Slalom, Women (Olympic)            Alpine Skiing (Skiing)
308407               Slalom, Women (Olympic)                               NaN

[238408 rows x 2 columns]