In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
print('probando 123')

probando 123

In [3]:
var1 = 2
var1

2

In [4]:
df = pd.read_excel('datasets/olympics-data.xlsx')
df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [5]:
df[df['athlete_id'] % 2 == 0 ]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27
...,...,...,...,...,...,...,...,...,...,...
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [6]:
df[df['born_city'].str.contains('pa', na = False, case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19
...,...,...,...,...,...,...,...,...,...,...
145086,148798,Nataliya Sherina,1999-05-24,Petropavlovsk-Kamchatsky,Kamchatka Kray,RUS,ROC,NaN,NaN,NaN
145378,149101,Cole McDonald,2003-03-06,Park City,Utah,USA,United States,NaN,NaN,NaN
145395,149118,Abbey Murphy,2002-04-14,Evergreen Park,Illinois,USA,United States,NaN,NaN,NaN
145421,149144,Nathan Smith,1998-10-19,Tampa,Florida,USA,United States,NaN,NaN,NaN
145441,149164,Casey Dawson,2000-08-02,Park City,Utah,USA,United States,NaN,NaN,NaN

In [7]:
df.loc[df['height_cm'].notna(), :]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [8]:
df[['born_city', 'born_date']].sample(20)

           born_city   born_date
87983        Morioka  1927-09-11
10631            NaN  1928-03-24
141570     Kėdainiai  1994-11-20
52560            NaN  1955-09-06
50633            NaN  1912-01-23
132272          León  1993-09-21
61349    Paris VIIIe  1902-04-13
80900        Bolzano  1975-03-20
72321            NaN  1968-10-10
30211            NaN  1939-12-23
127205        Jinhua  1992-09-18
125281           NaN  1987-07-02
51332            NaN  1969-11-25
67492          Paris  1961-06-14
8264       Khon Kaen  1968-03-03
98481   Sėrgėlėn sum  1937-10-14
37816         Košice  1908-07-20
116633         Minsk  1985-10-30
29049       Flushing  1965-10-11
116651     Ludington  1981-10-02

In [9]:
actual    = [0, 1, 2, 0, 2, 1]
predicted = [0, 2, 2, 0, 2, 1]

In [10]:
matrix = confusion_matrix(actual, predicted)
array = confusion_matrix(actual, predicted).ravel()

report = classification_report(actual, predicted, target_names=['number: 0', 'number: 1', 'number: 2'])

print(matrix, array)
print(report)

[[2 0 0]
 [0 1 1]
 [0 0 2]] [2 0 0 0 1 1 0 0 2]
              precision    recall  f1-score   support

   number: 0       1.00      1.00      1.00         2
   number: 1       1.00      0.50      0.67         2
   number: 2       0.67      1.00      0.80         2

    accuracy                           0.83         6
   macro avg       0.89      0.83      0.82         6
weighted avg       0.89      0.83      0.82         6

In [11]:
binary_true = [0, 0, 1, 1]
binary_pred = [0, 1, 0, 1]
binary = confusion_matrix(binary_true, binary_pred)
binary

array([[1, 1],
       [1, 1]])

In [12]:
# _____________ EJERCICIO DE REGRESION LINEAL _____________

# X = características (horas de estudio, horas de sueño)
X = np.array([
    [2, 5],   # Estudiante 1
    [3, 6],   # Estudiante 2
    [4, 4],   # Estudiante 3
    [5, 7],   # Estudiante 4
])
y = np.array([60, 70, 65, 80])

kf = KFold(n_splits=2, shuffle=True, random_state=42)
model = LinearRegression()

errors = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    errors.append(mse)
    
    nuevas_estadisticas = confusion_matrix(y_test, y_pred)
    report = classification_report(y_train, y_test)
    print('\n\n\n matriz de confusion \n', nuevas_estadisticas)
    print('\n\n\n clasification report \n', report)
    
    print("TRAIN INDEX:", train_index, "TEST INDEX:", test_index)
    print("valores resultados training: ", y_train)
    print("Valores reales:", y_test)
    print("Predicciones :", np.round(y_pred, 2))
    print("Error (MSE):", round(mse, 2))
    print("---------------")

print("Error promedio en todos los folds:", round(np.mean(errors), 2))

 matriz de confusion
 [[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]



 clasification report
               precision    recall  f1-score   support

          60       0.00      0.00      0.00       1.0
          65       0.00      0.00      0.00       1.0
          70       0.00      0.00      0.00       0.0
          80       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

TRAIN INDEX: [0 2] TEST INDEX: [1 3]
valores resultados training:  [60 65]
Valores reales: [70 80]
Predicciones : [61. 64.]
Error (MSE): 168.5
---------------



 matriz de confusion
 [[0 1 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]



 clasification report
               precision    recall  f1-score   support

          60       0.00      0.00      0.00       0.0
          65       0.00      0.00      0.00       0.0
          70       0.00      0.00      0.00       1.0
          80       0.00      0.00      0.00       1.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

TRAIN INDEX: [1 3] TEST INDEX: [0 2]
valores resultados training:  [70 80]
Valores reales: [60 65]
Predicciones : [64. 70.]
Error (MSE): 20.5
---------------
Error promedio en todos los folds: 94.5

c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\ccair\Documents\programming_stuff_5.1\review_sklearn\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [13]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# _____________ EJERCICIO DE REGRESION LINEAL _____________

# X = características (horas de estudio, horas de sueño)
import numpy as np
X = np.array([
    [2, 5],   # Estudiante 1
    [3, 6],   # Estudiante 2
    [4, 4],   # Estudiante 3
    [5, 7],   # Estudiante 4
])
y = np.array([60, 70, 65, 80])

kf_list = kf.split(X)
print(kf_list)

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[train_index]

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print("TRAIN INDEX:", train_index, "TEST INDEX:", test_index)
    print("Valores reales:", y_test)
    print("Predicciones :", np.round(y_pred, 2))
    print(f"MSE: {mse:.2f}, MAE: {mae:.2f}, R2: {r2:.2f}")
    print("---------------")

<generator object _BaseKFold.split at 0x0000020FE9795690>
TRAIN INDEX: [0 2] TEST INDEX: [1 3]
Valores reales: [60 65]
Predicciones : [61. 64.]
MSE: 1.00, MAE: 1.00, R2: 0.84
---------------
TRAIN INDEX: [1 3] TEST INDEX: [0 2]
Valores reales: [70 80]
Predicciones : [64. 70.]
MSE: 68.00, MAE: 8.00, R2: -1.72
---------------